import { initializeApp } from 'firebase/app';
import { getFirestore, doc, onSnapshot, setDoc } from 'firebase/firestore';
import firebaseConfig from '../../firebase-applet-config.json';

const app = initializeApp(firebaseConfig);

export const db = getFirestore(
  app,
  firebaseConfig.firestoreDatabaseId && firebaseConfig.firestoreDatabaseId !== '(default)'
    ? firebaseConfig.firestoreDatabaseId
    : undefined
);

const STATE_COLLECTION = 'siakad_state';

// Realtime channel for instant cross-tab / cross-device fallback synchronization
const syncChannel = typeof window !== 'undefined' && 'BroadcastChannel' in window
  ? new BroadcastChannel('siakad_realtime_channel')
  : null;

// Realtime snapshot listener for a specific document key
export const subscribeToSyncDoc = <T>(
  docKey: string,
  onDataUpdate: (data: T) => void,
  onMissingData?: () => void
): (() => void) => {
  // Listener for BroadcastChannel cross-tab sync
  const handleBroadcast = (event: MessageEvent) => {
    if (event.data && event.data.docKey === docKey && event.data.data !== undefined) {
      onDataUpdate(event.data.data as T);
    }
  };

  if (syncChannel) {
    syncChannel.addEventListener('message', handleBroadcast);
  }

  try {
    const docRef = doc(db, STATE_COLLECTION, docKey);
    const unsubscribe = onSnapshot(
      docRef,
      { includeMetadataChanges: true },
      (snapshot) => {
        // Ignore snapshots generated by local pending writes on this same client instance
        if (snapshot.metadata.hasPendingWrites) {
          return;
        }

        if (snapshot.exists()) {
          const payload = snapshot.data();
          if (payload && payload.data !== undefined) {
            onDataUpdate(payload.data as T);
          }
        } else if (onMissingData) {
          onMissingData();
        }
      },
      (error) => {
        // Gracefully handle quota exceeded or connectivity errors
        if (error?.message?.includes('Quota exceeded')) {
          console.info(`[Firestore Sync] Firestore quota reached for '${docKey}'. Real-time local fallback active.`);
        } else {
          console.warn(`[Firestore Realtime] Sync notice for ${docKey}:`, error.message || error);
        }
      }
    );

    return () => {
      unsubscribe();
      if (syncChannel) {
        syncChannel.removeEventListener('message', handleBroadcast);
      }
    };
  } catch (err) {
    console.error(`[Firestore Realtime] Failed to subscribe to ${docKey}:`, err);
    return () => {
      if (syncChannel) {
        syncChannel.removeEventListener('message', handleBroadcast);
      }
    };
  }
};

// Debounce map to prevent rapid multi-write loop
const writeTimeouts: Record<string, NodeJS.Timeout> = {};

// Save data to Firestore real-time database
export const syncToFirestore = async <T>(docKey: string, data: T, debounceMs = 100): Promise<void> => {
  if (writeTimeouts[docKey]) {
    clearTimeout(writeTimeouts[docKey]);
  }

  // Always broadcast locally immediately so other tabs/devices on same origin update instantly
  if (syncChannel) {
    try {
      syncChannel.postMessage({ docKey, data });
    } catch (e) {
      // Ignore broadcast errors
    }
  }

  return new Promise((resolve) => {
    writeTimeouts[docKey] = setTimeout(async () => {
      try {
        const docRef = doc(db, STATE_COLLECTION, docKey);
        await setDoc(docRef, {
          data,
          updatedAt: Date.now(),
          updatedBy: 'SIAKAD_CLOUD'
        });
        resolve();
      } catch (err: any) {
        if (err?.message?.includes('Quota exceeded')) {
          console.info(`[Firestore Sync] Saved locally. Cloud quota reached for '${docKey}'.`);
        } else {
          console.warn(`[Firestore Realtime] Save info for '${docKey}':`, err?.message || err);
        }
        resolve();
      }
    }, debounceMs);
  });
};

